version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle-ee
    ports:
      - "1521:1521"  # デフォルトのリスニングポート
      - "5500:5500"  # Enterprise Manager Expressポート
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: YourPassword123
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:

  oracle_data:
