/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

@RestController
@EnableAutoConfiguration
public class AppMain {

  public static void main(String[] args){
    SpringApplication.run(AppMain.class, args); 
  }

  @RequestMapping("/tip003")
  String home(){
    return "Hello, World!";
  }
 
}
